### ISSUE TITLE
extra insertion of owl:NamedIndividual

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/DIKB-Micropublication#25]
Extra unwanted owl:NamedIndividual's are being inserted when the reasoner is run to infer that evidence types are subclasses of data and methods.

**Comment by samuelrosko** [comment]
These are not extra owl:NamedIndividuals. It is necessary to have an owl:NamedIndividual for every drug ingredient (from ChEBI) and enzyme (from PRO) that is referenced in the mp:Claims or the np:Assertions. 

This is especially necessary because these owl:NamedIndividuals are what are used in the property chains for inference as designed by Mathias. This is an example of the alprazolam owl:NamedIndividual included in his Dideo_ISWC_Test.owl on the DIDEO Github:

    <owl:NamedIndividual rdf:about="&obo;CHEBI_2611">
        <rdf:type rdf:resource="&obo;CHEBI_24431"/>
        <rdfs:label xml:lang="en">alprazolam</rdfs:label>
        <obo:RO_0002449 rdf:resource="&obo;PR_000006130"/>
    </owl:NamedIndividual>
