### ISSUE TITLE
Ensure that all items from the old DIKB ABOUT DRUGS are in the new DIKB

### ISSUE THREAD

**Issue by ningyifan** [dbmi-pitt/DIKB-Micropublication#29]
Issues:

Claim-41:  

- https://dbmi-icode-01.dbmi.pitt.edu/dikb-evidence/fluvoxamine_increases_auc_thioridazine.html. A statement that should support this claim but it is not present

Claim-105: 

- Why are there 3 data items challenging the claim? Should be only 1. We think this is because the inferred-dikb-mp-fold-[1-5].xml graphs are loaded on the public facing endpoint - these should not be there but on the development server.

**Comment by jodischneider** [comment]
TODO: identify similar QA issues

**Comment by samuelrosko** [comment]
I have updated the CSV file to include the information that was previously missing.

I attempted to do this manually, but it was taking too long, so I switched to a different approach and edited the query script that Yifan had made.

The issue was that sometimes, not all of the information was included, ie number of participants, which excluded the information from the CSV file, which is not how that should be. I edited the file so this is not the case. 

However, this does not conclude the QA issue here. By using ChEBI identifiers, which we are deriving from DrugBank identifiers, we are missing a number of drugs, and, subsequently, assertions from the old DIKB. I have attempted to fix this problem by manually adding DB to ChEBI mappings for drugs that were common enough for me to recognize, but this is by no means complete.

We will have to identify a better mapping system or accept a loss of data in the transition from old to new DIKB.

**Comment by jodischneider** [comment]
ChEBI mappings updated.
8 metabolites that do not have ChEBI identifiers are still pending -- see JoCHEM http://biosemantics.org/index.php/resources/jochem

**Comment by rkboyce** [comment]
Here are the umapped metabolites....

object: demethylcitalopram
object: R-demethylcitalopram
object: S-demethylcitalopram
object: clozapine-N-oxide
object: demethylcitalopram
object: desacetyldiltiazem
object: N-demethyldesacetyl-diltiazem
object: R-demethylcitalopram
object: S-demethylcitalopram
object: beta-hydroxy-lovastatin
object: beta-hydroxy-simvastatin
object: dehydro-aripiprazole
object: demethylcitalopram
object: N-desalkylquetiapine
object: R-demethylcitalopram
object: reduced-haloperidol
object: S-demethylcitalopram
object: hydroxybupropion

**Comment by jodischneider** [comment]
All drugs from old-DIKB are included. All metabolites are skipped.
