### ISSUE TITLE
Claim is already a Statement

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/DIKB-Micropublication#4]
It's not wrong, but not necessary, to assert that 

s rdf:type Claim
s rdf:type Statement

Claims are always Statements. So just use s rdf:type Claim

**Comment by samuelrosko** [comment]
This is not longer the case, but what is the case now is:

            graph.add((poc[currentAnnotationClaim],RDF.type, mp["Claim"]))
            graph.add((poc[currentAnnotationClaim],RDF.type, mp["Representation"]))

Does this make sense to you? It does not to me... If you look at the MP paper, it says:

f. A Representation is an Artifact which represents something.

g. A Representation may be a Sentence, Data, Method, Micropublication, Attribution, or ArticleText. 

So that should be removed and it should just be a claim, correct?

**Comment by jodischneider** [comment]
TODO:  Remove graph.add((poc[currentAnnotationClaim],RDF.type, mp["Representation"])) -- we will get this from the inferencing (using MP OWL file).

**Comment by samuelrosko** [comment]
Yifan implemented this change at roughly 4PM on 2015-07-29.
